# If conda activate does not work in PowerShell, use this command:
# conda init powershell

# This file may be used to create an environment using:
# conda env create --file=environment.yaml

# A different name can be selected for the new environment:
# conda env create --name=work_new --file=environment.yaml

# An existing environment can be updated:
# conda env update --name=work_old --file=environment.yaml

# Keep pip installations to a minimum, and install
# dependencies with conda instead. To test, use:
# pip install oemof --dry-run

# Common errors:

# "Cannot mix incompatible Qt library (5.15.8) with this library (5.15.6)"

# Qt is a library for graphical user interfaces.
# This error can occur when you have separate conda environments with
# different versions of the package "PyQt5". It should be solved by
# making sure your new environments use the same version as your base
# environment.
# In the example above, we can run the command
# "conda list qt"
# to find the actual package name that causes the issue and then
# "conda install qt-main==5.15.6"

name: work
channels:
    - jnettels
    - conda-forge
    - defaults
dependencies:
    - python
    - pip
    - pandas
    - pyyaml
    - numpy >=2.0
    # - scipy <1.16  # in case of issues with tobler
    - numba
    - geopandas >=1.0
    - matplotlib
    - osmnx >=1.9.4
    - momepy
    - coolprop
    - fiona
    - gdal >=3.7  # Fix for CityGML
    - tobler
    - h3-py
    - contextily
    - libpysal
    - shapely >=2.0
    - openpyxl
    - fuzzywuzzy
    - joblib
    - mapclassify

    # From channel jnettels
    - lpagg >=0.19

    # dhnx/oemof dependencies:
    - PyUtilib
    - Pyomo >=6.8.0
    - addict
    - blinker
    - dill
    - nose

    # pandapipes/pandapower dependencies
    - deepdiff
    - geojson

    # Specify automatic pip installations
    - pip:
        - https://github.com/oemof/DHNx/archive/dev.tar.gz  # dhnx (branch 'dev')
        - oemof.solph >=0.6
        - demandlib >=0.2.2
        - pandapipes >=0.12
        - pandapower <3.2  # https://github.com/e2nIEE/pandapipes/issues/770
