# If conda activate does not work in PowerShell, use this command:
# conda init powershell

# This file may be used to create an environment using:
# conda env create --file environment.yaml

# Keep pip installations to a minimum, and install
# dependencies with conda instead. To test, use:
# pip install oemof --dry-run

# Common errors:

# "Cannot mix incompatible Qt library (5.15.8) with this library (5.15.6)"

# Qt is a library for graphical user interfaces.
# This error can occur when you have separate conda environments with
# different versions of the package "PyQt5". It should be solved by 
# making sure your new environments use the same version as your base
# environment.
# In the example above, we can run the command
# "conda list qt" 
# to find the actual package name that causes the issue and then
# "conda install qt-main==5.15.6" 

name: work
channels:
    - jnettels
    - conda-forge
dependencies:
    - python=3.10
    - pandas
    - numpy
    - geopandas
    - matplotlib
    - osmnx
    - coolprop
    - fiona
    - tobler
    - h3-py
    - contextily
    - libpysal
    - shapely
    - pygeos
    - openpyxl
    - lpagg
    - trnpy
    # For SQL stuff
    # sqlalchemy
    # geoalchemy2
    # psycopg2

    # Spyder dependencies: (If you want to activate the environment in a spyder console)
    # spyder-kernels=2.3  # Version number was provided by a spyder error messsage

    # dhnx/oemof dependencies:
    - PyUtilib
    - Pyomo
    - addict
    - blinker
    - dill
    - nose

    # pandapipes dependencies
    deepdiff


# run manual pip installations afterwards 
# check with dry run first, to install missing packages with conda
# pip install oemof.network oemof.solph oemof.tools --dry-run

# for dhnx, you can manually download the latest
# version from the 'dev' branch of https://github.com/oemof/DHNx
# and run
# pip install -e <path to DHNx>
# or
# conda develop <path to DHNx>
#
# As of May 2023, it should be save to install dhnx 0.0.3 directly
# pip install dhnx==0.0.3 --dry-run

# Pandapipes needs to be installed from pip
# pip install pandapipes --dry-run
