{% set data = load_setup_py_data() %}

# Run this build with conda-forge channel, due to dependencies:
# conda build conda.recipe -c conda-forge

package:
  name: dhnx_addons
  version: {{ data['version'] }}

source:
    path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

  script:
        - pip install .

  noarch: python

  preserve_egg_dir: True

requirements:
    build:
        - python
        - setuptools_scm
    run:
        # dhnx_addons dependencies
        - python
        - pandas
        - numpy <2.0  # required by pandapower<3.0
        - numba
        - geopandas
        - matplotlib
        - osmnx >=1.9.4
        - momepy
        - coolprop
        - fiona
        - gdal >=3.7  # Fix for CityGML
        - rasterio
        - tobler
        - h3-py
        - contextily
        - libpysal
        - shapely >=2.0
        - openpyxl
        - fuzzywuzzy
        - owslib
        - joblib

        # From channel jnettels
        - lpagg >=0.18.0

        # dhnx/oemof dependencies:
        - PyUtilib
        - Pyomo >=6.8.0
        - addict
        - blinker
        - dill
        - nose

        # pandapipes dependencies
        - deepdiff

        # The following dependencies are installed via pip
        # They are listed here only for reference
        # - dhnx
        # - oemof.solph
        # - demandlib
        # - pandapipes

about:
    home: https://github.com/jnettels/dhnx_addons
    summary: 'Collection of GIS functions'
    description: 'Collection of GIS functions'
    license: 'MIT'
    license_file: 'LICENSE'
    author: 'Joris Zimmermann'
    author_email: 'joris.zimmermann@siz-energieplus.de'
