name: Publish Releases

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    name: Publish
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v1  # use the latest code commit

    - name: Setup conda with python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: work
        environment-file: environment_dev.yaml
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies with conda
      shell: pwsh  # Needed where conda env is used
      run: |
        conda install anaconda-client conda-build setuptools setuptools_scm

    - name: Build & upload with conda
      shell: pwsh  # Needed where conda env is used
      run: |
        # Login to anaconda (answer the resulting prompt with yes)
        echo y | anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }} --hostname "GitHub_dhnx_addons_${{ matrix.os }}_${{ matrix.python-version }}"
        # Enable automatic upload to anaconda.org
        conda config --set anaconda_upload yes
        # Run build process
        conda build conda.recipe -c conda-forge -c jnettels
