name: Python Jobs

on: [push, pull_request]

jobs:
  job_1:
    runs-on: ${{ matrix.os }}
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
        dhnx-version: ["pip", "github"]

    steps:
    - name: Checkout
      uses: actions/checkout@v1  # use the latest code commit

    - name: Setup conda with python ${{ matrix.python-version }}
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies with conda
      run: |
        conda install --file requirements.txt -c conda-forge -c jnettels

    - name: Install DHNx from pip
      if: matrix.dhnx-version == 'pip'
      run: |
        pip install dhnx==0.0.3

    - name: Install DHNx from GitHub
      if: matrix.dhnx-version == 'github'
      run: |
        git clone https://github.com/oemof/DHNx
        cd DHNx
        git checkout fix/logger-usage
        pip install -e .

    - name: Install special demandlib branch from GitHub
      run: |
        git clone https://github.com/jnettels/demandlib
        cd demandlib
        git checkout features/add-vdi-from-lpagg
        conda develop ./src

    - name: Install solver cbc (Windows)
      if: runner.os == 'Windows'
      run: echo y | python dhnx_addons/cbc_installer.py

    - name: Install solver cbc (Linux)
      if: runner.os == 'Linux'
      run: sudo apt install coinor-cbc -y

    - name: Run OpenStreetMap example workflow
      run: |
        cd dhnx_addons
        python dhnx_addons.py

    - name: Lint with flake8
      if: runner.os == 'Linux'  # Only needs to run once
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
