name: Python Jobs

on: [push, pull_request]

jobs:
  job_1:
    runs-on: ${{ matrix.os }}
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.12", "3.13"]

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Install package and test dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U build wheel
        python -m pip install -e .[dev]

    - name: Lint with flake8
      if: runner.os == 'Linux'
      shell: bash
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install solver cbc (Windows)
      if: runner.os == 'Windows'
      run: echo y | python src/dhnx_addons/cbc_installer.py

    - name: Install solver cbc (Linux)
      if: runner.os == 'Linux'
      run: sudo apt install coinor-cbc -y

    - name: Run OpenStreetMap example workflow
      if: runner.os == 'Linux' # Just hangs on windows for unknown reasons
      shell: bash
      run: |
        cd ./examples
        python dhnx_example.py

  job_2:
    runs-on: ${{ matrix.os }}
    name: Build package
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.12", "3.13"]

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Build distributions
      shell: bash
      run: |
        python -m pip install --upgrade pip build
        python -m build
